### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by ghost** [gottsch/gottsch-minecraft-EnemyEchelons#8]
https://mclo.gs/w5ytN2f

**Comment by ghost** [comment]
Are this gonna be fixed or this mod is abandoned?

**Comment by gottsch** [comment]
> Are this gonna be fixed or this mod is abandoned?

It is not abandoned. I'm just very busy with another project at the moment.

It looks like it can't read the eechelons-config file. Did you edit it at all? It could be just a missing quote or something.

**Comment by ghost** [comment]
Thank you very much for your answer. Yes, you're right, I forgot a detail in config. Good luck with your another project. And also thank you for this mod, it is really helping me in creating my RPG-modpack
